##**CREATING A NUMPY ARRAY AND ITS ATTRIBUTES**

In [ ]:
#importing numpy library
import numpy as np
my_list = [1,2,3,4,5]  #Creating a list named "my_list"
my_array = np.array(my_list) #Creating a 1-D numpy array from "my_list"
print(my_array)

arr_0d = np.array(42) #Creating a 0-D numpy array
print(arr_0d)

arr_2d = np.array([[1,2,3],[4,5,6]]) #Creating a 2-D numpy array
print(arr_2d)

arr_3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]) #Creating a 3-D numpy array
print(arr_3d)


[1 2 3 4 5]
42
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#Creating array and its attributes

arr = np.array([[1,2,3,4],[6,7,8,9]])

print(arr) #Printing the array
print(arr.ndim) #Printing the dimension of the array
print(arr.shape) #Printing the shape of the array
print(arr.size) #Printing the size of the array
print(arr.dtype) #Printing the data type of the array

[[1 2 3 4]
 [6 7 8 9]]
2
(2, 4)
8
int64


ACCESING AND MANUPLITING ARRAY ELEMENTS

NEGATIVE INDEXING


In [ ]:
#Accesing 2-D  array elements with negative indexing

my_arr = np.array([[2,5,7,9],[1,3,5,7]])
print(my_arr[1,-2])

5


SLICING ARRAYS

####IMPORTANT CONCEPT WHILE SLICING
#####      array [start:end]
#####      array [start:end:step]

In [ ]:
arr = np.array([1,3,5,7,9,11,13,15,17,19,21])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])


[3 5 7 9]
[ 9 11 13 15 17 19 21]
[1 3 5 7]
[17 19]
[3 7]


In [ ]:
#Slicing a 2-D numpy Array
arr = np.array([[1,3,5,7],[2,4,6,8]])
print(arr[1,1:-1])
print(arr[0:2,2])
print(arr[0:2,1:4])


[4 6]
[5 6]
[[3 5 7]
 [4 6 8]]


**CLASSWORK**

1. Create a NumPy array from the list [7, 14, 21, 28]. Print the array.

In [ ]:
import numpy as np
list = [7,14,21,28]
arr = np.array(list)
print (arr)

[ 7 14 21 28]


2. Create a 2D NumPy array [[5, 10, 15], [20, 25, 30]]. Print its shape and num- ber of dimensions using array. ndim.

In [ ]:
arr_2D = np.array([[5,10,15],[20,25,30]])
print(f"The arrays dimension is : {arr_2D.ndim}"  )
print(f"The arrays shape is : {arr_2D.shape}"  )
print(f"The arrays size is : {arr_2D.size}"  )


The arrays dimension is : 2
The arrays shape is : (2, 3)
The arrays size is : 6


3. Use np. zeros to create a 2D array of shape (2, 3). Then, use np.arange to create an array from 0 to 12 with a step of 3. Print both arrays.

In [ ]:
# 1. Create a 2D array of shape (2, 3) filled with zeros
zeros_array = np.zeros((2, 3))

# 2. Create a 1D array from 0 to 12 with a step of 3
arange_array = np.arange(0, 13, 3)

# 3. Print both arrays
print("2D Zeros Array (2x3):")
print(zeros_array)

print("\n1D Arange Array from 0 to 12 (step 3):")
print(arange_array)

2D Zeros Array (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]

1D Arange Array from 0 to 12 (step 3):
[ 0  3  6  9 12]


4. Create a NumPy array [2, 4, 6, 8]. Multiply all elements by 3 and print the result.

In [ ]:
# Create the array
arr = np.array([2, 4, 6, 8])

# Multiply all elements by 3
result = arr * 3

# Print the result
print("Original Array:")
print(arr)

print("\nAfter Multiplying by 3:")
print(result)

Original Array:
[2 4 6 8]

After Multiplying by 3:
[ 6 12 18 24]


5. Create a NumPy array [1, 3, 5, 7, 9, 11]. Print the third element and a slice from index 1 to 3 (inclusive).

In [ ]:
arr = [1,3,5,7,9,11]
print(arr[2])
print(arr[1:4])


5
[3, 5, 7]
