**HOMEWORK**

### 1. Create a 2D NumPy array of shape (3, 3) with random integers between 1 and 10 (inclusive) using np.random.randint. Then, replace all values greater than 5 with O and print the modified array. 2. Create two 1D NumPy arrays: [2, 4, 6, 8] and [1, 3, 5, 7]. Compute the element-wise sum and the dot product of the two arrays. Print both results.

In [3]:
import numpy as np

# Question 1
print("Question 1:")
# Create a 2D NumPy array of shape (3, 3) with random integers between 1 and 10
arr_2d = np.random.randint(1, 11, size=(3, 3))
print("Original array:")
print(arr_2d)

# Replace all values greater than 5 with 0
arr_2d[arr_2d > 5] = 0
print("Modified array (values > 5 replaced with 0):")
print(arr_2d)

# Question 2
print("\nQuestion 2:")
# Create two 1D NumPy arrays
arr_a = np.array([2, 4, 6, 8])
arr_b = np.array([1, 3, 5, 7])

print("Array a:", arr_a)
print("Array b:", arr_b)

# Compute the element-wise sum
element_wise_sum = arr_a + arr_b
print("Element-wise sum:", element_wise_sum)

# Compute the dot product
dot_product = np.dot(arr_a, arr_b)
print("Dot product:", dot_product)

Question 1:
Original array:
[[ 8  3  9]
 [ 2  2  8]
 [ 8 10  7]]
Modified array (values > 5 replaced with 0):
[[0 3 0]
 [2 2 0]
 [0 0 0]]

Question 2:
Array a: [2 4 6 8]
Array b: [1 3 5 7]
Element-wise sum: [ 3  7 11 15]
Dot product: 100


### 2. Create two 1D NumPy arrays: [2, 4, 6, 8] and [1, 3, 5, 7]. Compute the element-wise sum and the dot product of the two arrays. Print both results.

In [4]:
# Create two 1D NumPy arrays
arr_a = np.array([2, 4, 6, 8])
arr_b = np.array([1, 3, 5, 7])

print("Array a:", arr_a)
print("Array b:", arr_b)

# Compute the element-wise sum
element_wise_sum = arr_a + arr_b
print("Element-wise sum:", element_wise_sum)

# Compute the dot product
dot_product = np.dot(arr_a, arr_b)
print("Dot product:", dot_product)

Array a: [2 4 6 8]
Array b: [1 3 5 7]
Element-wise sum: [ 3  7 11 15]
Dot product: 100


###3. Create a 2D NumPy array of shape (4, 3) filled with ones using np.ones. Then, add a 1D array [10, 20, 30] to each row of the 2D array using broadcasting. Print the resulting array.

In [5]:
# Create a 2D NumPy array of shape (4, 3) filled with ones
array_2d = np.ones((4, 3))
print("Original 2D array:")
print(array_2d)

# Create a 1D array
array_1d = np.array([10, 20, 30])
print("\n1D array to add:")
print(array_1d)

# Add the 1D array to each row of the 2D array using broadcasting
# NumPy's broadcasting rules allow this operation as the 1D array's shape (3,)
# is compatible with the last dimension of the 2D array (also 3).
result_array = array_2d + array_1d
print("\nResulting array after adding 1D array to each row:")
print(result_array)

Original 2D array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1D array to add:
[10 20 30]

Resulting array after adding 1D array to each row:
[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


### 4. Create a 2D NumPy array [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Extract the second column and compute its mean using np.mean. Then, reshape the original array into a 1D array and print both results.
.con

In [6]:
# Create the 2D NumPy array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
print("Original 2D array:")
print(original_array)

# Extract the second column (index 1)
second_column = original_array[:, 1]
print("\nSecond column extracted:")
print(second_column)

# Compute the mean of the second column
mean_of_second_column = np.mean(second_column)
print("Mean of the second column:", mean_of_second_column)

# Reshape the original array into a 1D array
# Using .reshape(-1) flattens the array into a 1D array
reshaped_array_1d = original_array.reshape(-1)
print("\nOriginal array reshaped into a 1D array:")
print(reshaped_array_1d)

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second column extracted:
[2 5 8]
Mean of the second column: 5.0

Original array reshaped into a 1D array:
[1 2 3 4 5 6 7 8 9]


### 5. Create a 1D NumPy array [10, 20, 30, 40, 50, 60]. Use a boolean mask to select elements greater than 30, then square those elements. Print the original array and the modified array.


In [7]:
# Create the 1D NumPy array
original_array = np.array([10, 20, 30, 40, 50, 60])
print("Original array:")
print(original_array)

# Create a boolean mask for elements greater than 30
boolean_mask = original_array > 30
print("\nBoolean mask (elements > 30):")
print(boolean_mask)

# Select elements greater than 30 and square them
# We create a copy to avoid modifying the 'original_array' in place if we want to print both.
# If modifying original_array was fine, we could just do original_array[boolean_mask] = original_array[boolean_mask] ** 2
modified_array = np.copy(original_array)
modified_array[boolean_mask] = modified_array[boolean_mask] ** 2

print("\nModified array (elements > 30 squared):")
print(modified_array)

Original array:
[10 20 30 40 50 60]

Boolean mask (elements > 30):
[False False False  True  True  True]

Modified array (elements > 30 squared):
[  10   20   30 1600 2500 3600]
